dist: trusty
sudo: false

language: node_js
node_js:
  - '8.16.0'

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run lint
  - npm install pbiny -g
  - pbiny -h
  - pbiny -v
  - pbiny up -h
  - pbiny usr